language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - "6"
  - "8"
  - "10"
before_install:
  - npm i -g yarn --cache-min 999999999
install:
  - yarn
notifications:
    email: false
before_script:
  - yarn add codecov --dev
after_script:
  - codecov
git:
  depth: 5